services:
  app:
    build:
      context: .
      args:
        BUILDPLATFORM: linux/amd64
    platform: linux/amd64
    ports:
      - "3005:3005"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
