version: '3'
services:
  app:
    build:
      context: .
      args:
        BUILDPLATFORM: linux/arm64
    platform: linux/arm64
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT= ${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - .:/app
      - /app/node_modules
